cart/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
# from goods import views
# from goods.views import *
# from . import views
from .views import *

urlpatterns = [
    # ajax post  ajax post 请求必须有csrf 验证
    url(r'^add/$', AddCart.as_view(), name='add'),
    url(r'^info/$', CartInfo.as_view(), name='info'),
    url(r'^update$', UpdateCart.as_view(), name='update'),
    url(r'^delete$', DeleteCart.as_view(), name='delete'),  # DeleteCart
]

d/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import tinymce.urls
from rest_framework.routers import DefaultRouter

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),  # haystack 路由/search/?q=草莓
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车
    url(r'^order/', include('orders.urls', namespace='order')),  # 订单模块
    url(r'^api-auth/', include('rest_framework.urls')), # drf
    url(r'^', include('goods.urls', namespace='goods')),
]

goods/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import include, url
# from goods import views
# from goods.views import *
# from . import views
from .views import *
# drf
from rest_framework.documentation import include_docs_urls

# 1. router 的使用导入包
from rest_framework.routers import DefaultRouter
# 2. 导入views里面的viewsets 视图
from .views import GoodApiViewsetsView

# 3. 创建router对象
router = DefaultRouter()  # 默认get 绑list post 绑定create
# 4.注册路由 绑定viewsets,viewsets 重写了as_view并且给request绑定了.action
router.register(r"^apiaa", GoodApiViewsetsView, base_name="apiaa")
router.register(r'^apicat', GoodCategoryViewset, base_name="category")

# apigg 结果直接放进到url填坑就可以了 非router注册
apigg = GoodApiViewsetsView.as_view({
    "get": "list",  # 自己绑定
    "post": "create",
})

urlpatterns = [
    # 5. 把注册好的路由包含进来
    url(r'^', include(router.urls)),
    url(r'^$|^index$', IndexView.as_view(), name='index'),  # 神马都没有
    url(r'^detail/(?P<sku_id>\d+)$', DetailView.as_view(), name='detail'),  # DetailView /id 才能url让别人看到
    # list/category_id/page_num?.
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)$', ListView.as_view(), name='list'),
    # DetailView /id 才能url让别人看到
    url(r'^mysearch/$', MySearchView.as_view(), name='list'),  # DetailView /id 才能url让别人看到

    url(r'^apigoodold/', GoodViewOld.as_view(), name="learn1"),
    url(r'^apigood/', GoodAPIView.as_view(), name="learn2"),
    url(r'^apig/', GoodApiMiXinView.as_view(), name="learn3"),
    # url(r'^apigg/', GoodApiViewsetsView.as_view(), name="learn4"),
    url(r'^apigg/', apigg, name="learn5"),
    url(r'docs/', include_docs_urls(title='pxd')),

]

orders/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
# from goods import views
# from goods.views import *
# from . import views
from .views import *

urlpatterns = [
    # /order/place
    url(r'^place$', PlaceOrderView.as_view(), name='place'),
    # /order/commit POST
    url(r'^commit$', CommitOrderView.as_view(), name='commit'),
    # /order/1   page 第几页
    url(r'^(?P<page>\d+)$', UserOrderView.as_view(), name='info'),
    # /order/pay POST
    url(r'^pay$', PayView.as_view(), name='pay'),
    # /order/checkpay GET
    url(r'^checkpay$', CheckPayView.as_view(), name='checkpay'),
    url(r'^comment/(?P<order_id>\d+)$', OrderCommentView.as_view(), name='comment'),

]

users/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from users.views import *  # 导包路径限制的 from apps.users.views import * 是错的

# from users import view
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # 函数视图注册
    # url(r"^register$", views.register, name="register")
    # 类视图注册  如何在正则表达式中调用类视图，用类名.as_view()函数
    url(r"^register$", RegisterView.as_view(), name="register"),
    url(r"^active/(?P<token>.+)$", ActiveView.as_view(), name="active"),
    url(r"^login$", Login.as_view(), name="login"),
    url(r"^logout$", Logout.as_view(), name="logout"),
    url(r"^address$", AddressView.as_view(), name="address"),
    url(r"^userinfo$", UserInfoView.as_view(), name="userinfo"),

    # 装饰器原理 @login_required === >  login_required(Addresss.as_view())
    # url(r"^address$", login_required(Address.as_view()), name="address"),
]

"""
login_required([redirect_field_name=REDIRECT_FIELD_NAME, login_url=None])
第一个参数是next = ？ next的名字 默认next
第二个参数是登陆失败校验不通过情况下跳转的页面，
第二个参数如果都不设置的话 可以仅仅设置settings.py 中 
LOGIN_URL = '/users/login' 即可！
"""

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import *
from goods.models import *
from django_redis import get_redis_connection
import json

# 商品详情页面,添加购物车 ==> 入口,登陆和非登陆都可以添加
#  购物车存储到redis 用 hash 哈希存储
#  hmset cart_userid1 草莓(sku_id)=>2 芒果(sku_id) 3
# eg: cart_1 1:3 2:2 3:1 ...... 字段名是sku_id value是个数
# 读取方法 cart_dict = redis_coon.hgetall('cart_userid')
# cart_dict={ sku_id:count1, sku_id2:count2 }
# 注意:如果涉及到比较和计算注意统一转换对应的类型
#  for val in cart_dict.values():
#       pass
#
# ############################################################# #

# 加入购物车
# 收集 user_id  sku_id count 3个信息
# hset cart_userid sku_id count
# ajax post 请求!
"""
{
'code':0,
'message':'添加购物车成功'
}
{
'code':1,
'message':'用户未登录'
}
{
'code':1,
'message':'库存不足'
}
"""


class AddCart(View):
    def post(self, request):
        """接受购物车参数,校验,保存"""
        """(django_redis为什么要保存bytes字节的,读取和写入速度是最快的)"""
        '''"cart:{'sku_id1':count1,'sku_id2':count2}" cookie使用json字符串
                  因为浏览器的同源策略,每个用户的cookie是自己的所以键可以是重复的,
                  用户每次请求只会带上自己的cookie,不会带上别人的可以区分每个人,所以key可以是一样的cart可以这么使用
                  json 模块 技术支持
                  json.dumps   字典转json字符串
                  json.loads   json字符串转字典
                  注: 转换过程中value的类型不变,进入如一'''
        # 判断用户是否登陆
        # if not request.user.is_authenticated():
        #     return JsonResponse({'code': 1, 'message': '用户未登陆'})  # 先做登陆的
        # 接受购物车参数,user_id,sku_id count  ,信息

        sku_id = request.POST.get('sku_id')  # 字符串
        count = request.POST.get('count')  # 字符串

        # 校验参数all() user_id 不需要校验 因为购物车不需要登陆,登陆里面直接通过request.user.idd 取就可以了
        if not all([sku_id, count]):
            return JsonResponse({'code': 2, 'message': '缺少参数'})
        # 校验sku_id 是否合法
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 3, 'message': '缺少参数'})
        # 校验count 是否合法
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'code': 4, 'message': '商品数量错误'})

        # 判断库存是否超出,加入购物车的数量和库存比较
        if count > sku.stock:
            return JsonResponse({'code': 5, 'message': '库存不足'})
        if request.user.is_authenticated():
            # 保存购物车数据到redis
            redis_con = get_redis_connection('default')
            # 需要查询该用户保存到购物车的sku_id数据是否存在,如果存在的话累加,不存在的话直接赋值OK!
            origin_count = redis_con.hget('cart_%s' % request.user.id, sku_id)
            if origin_count is not None:  # 存在累加
                count += int(origin_count.decode())  # django_redis保存的是bytes字节类型需要转换
            # 累加完毕以后再次判断库存
            """问题?每个用户都能添加98个逻辑是否正确"""
            if count > sku.stock:
                return JsonResponse({'code': 5, 'message': '库存不足'})
            redis_con.hset('cart_%s' % request.user.id, sku_id, count)  # 有问题!重复的会被覆盖,应该先查询一下判断是否累加

            # 前台需要展示购物车的总数量这里需要查询redis 计算总数量
            cart_dict = redis_con.hgetall('cart_%s' % request.user.id)
            cart_num = 0
            for v in cart_dict.values():
                cart_num += int(v.decode())
            # 相应JsonResponse 根据情况不同code不同json不同
            return JsonResponse({'code': 0, 'message': '添加购物车成功', 'cart_num': cart_num})
        else:  # 用户未登陆
            # cookie =>'cart' : '{'1':1,'2':3}'
            cookies_str = request.COOKIES.get('cart')  # '{'1':1,'2':3}'
            if cookies_str:  # 和redis一样存在累加
                cart_dict = json.loads(cookies_str)  # {'1':1,'2':3}
            else:
                cart_dict = {}
            # 需要保证sku_id=》 cart_dict 的key的类型一致才能in
            if sku_id in cart_dict:  # {'1':1,'2':3} 刚好sku_id 是字符串类型ｏｋ
                number = cart_dict[sku_id]  # 转换过程中value的类型不变
                count += number  # 走到这里count肯定是数字转换过了
            if count > sku.stock:  # cookie 也要再次判断累加后的库存
                return JsonResponse({'code': 5, 'message': '库存不足'})
            # 更新最新的（累加过或者全新的）字典
            cart_dict[sku_id] = count
            cart_num = 0
            # 计算cookie中的购物车总数
            for value in cart_dict.values():
                cart_num += value  # 这里不需要转换 存的时候是int
            cart_str = json.dumps(cart_dict)
            # 创建response => render JsonResponse HttpResponse HttpRedirect Redirect 五大类都可以返回response
            response = JsonResponse({'code': 0, 'message': '添加购物车成功', 'cart_num': cart_num})
            response.set_cookie('cart', cart_str)
            return response

            # 伪代码
            # response.set_cookie('cart','cart_json')


class UpdateCart(View):
    def post(self, request):
        """+ -  手动输入购物车"""
        # 获取参数 sku_id count
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 校验参数all
        if not all([sku_id, count]):
            return JsonResponse({'code': 1, 'messsage': '缺少参数'})
        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'messsage': '商品不存在'})
        # 判断count是否是int
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'code': 3, 'messsage': '商品数量错误'})
        # 判断库存
        if count > sku.stock:
            return JsonResponse({'code': 3, 'messsage': '库存不足'})
        # 判断用户是否登陆
        if request.user.is_authenticated():
            # 如果用户登陆,将修改的购物车信息存储导redis中
            redis_con = get_redis_connection('default')
            # 幂等做法
            redis_con.hset('cart_%s' % request.user.id, sku_id, count)
            return JsonResponse({'code': 0, 'messsage': 'ok!'})
            # # 非幂等做法
            # cart_dict = redis_con.hgetall()
            # if sku_id.encode() in cart_dict:
            #     origin_count = cart_dict[sku_id.encode()]
            #     count += int(origin_count.decode())
            # cart_dict[sku_id.encode()] = count
        else:
            # 如果用户没有登陆 存储用户修改的购物车信息到cookie中
            cookies_str = request.COOKIES.get('cart')
            if cookies_str:
                cart_dict = json.loads(cookies_str)
            else:
                cart_dict = {}
            cart_dict[sku_id] = count
            cookies_str = json.dumps(cart_dict)
            # 响应对应的JsonResponse
            http_response = JsonResponse({'code': 0, 'messsage': 'ok!'})
            http_response.set_cookie('cart', cookies_str)
            return http_response


class DeleteCart(View):
    def post(self, request):
        # 接受参数
        sku_id = request.POST.get('sku_id')
        # 校验参数all
        if not sku_id:
            return JsonResponse({'code': 1, 'message': '参数sku_id不能为空'})
        # 判断sku_id是否合法
        try:
            GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 1, 'message': '删除的商品sku_id不存在'})
        # 判断用户是否登陆  # 响应对应的JsonResponse
        if request.user.is_authenticated():
            # 登陆删除redis
            redis_conn = get_redis_connection('default')
            redis_conn.hdel('cart_%s' % request.user.id, sku_id)  # hdel(userinfo,name)删除一个字段
            return JsonResponse({'code': 0, 'message': '删除ok!'})
        else:
            # 未登录删除cookie
            cookies_str = request.COOKIES.get('cart')
            if cookies_str:
                cart_dict = json.loads(cookies_str)
                del cart_dict[sku_id]
                cookies_str = json.dumps(cart_dict)
                response = JsonResponse({'code': 0, 'message': '删除ok!'})
                response.set_cookie('cart', cookies_str)
                return response
            else:
                return JsonResponse({'code': 1, 'message': '购物车为空不能删除!'}) # 恶意调用删除


class CartInfo(View):
    """用户不用登陆就可以看购物车信息"""

    def get(self, request):
        """用户登陆和未登录时，查询购物车信息，并且渲染页面==> 购物车列表"""
        if request.user.is_authenticated():
            redis_client = get_redis_connection('default')
            user_id = request.user.id
            # redis读取出来的是bytes类型，读写速度最快
            cart_dict = redis_client.hgetall('cart_%s' % request.user.id)
        else:
            cookie_str = request.COOKIES.get('cart')
            if cookie_str:
                # 字典类型 {'1':1,'2':2}
                cart_dict = json.loads(cookie_str)
            else:
                cart_dict = {}
        total_money_amount = 0
        totol_count = 0
        temp_arr = []
        for sku_id, count in cart_dict.items():
            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                continue

            sku.count = int(count)  # 统一处理redis和cookie  动态属性 数量
            # 小计 商品的价格 X 数量
            sku.amount = sku.count * sku.price  # 动态属性 小计
            total_money_amount += sku.amount  # 只有cart_dict 字典是不够的，还要把小计传过去,所以记录，需要列表嵌套多个GoodsSKU对象
            # 并且多个GoodsSKU对象动态的添加小计和总数，动态语言的特性
            totol_count += sku.count
            temp_arr.append(sku)
        # 构造上下文
        context = {
            'total_amount': total_money_amount,  # 总金额
            'totol_count': totol_count,  # 总个数
            'skus': temp_arr,
        }
        # 渲染模板
        return render(request, 'cart.html', context)

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load staticfiles %}

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- 顶部引用js script 标签模块 -->
    {% block topfiles %}
        <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock topfiles %}
</head>

<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            <!-- base做过判断子模板无需判断 父模板可以拿子模板的内容 -->
            {% if user.is_authenticated %}
                <div class="login_btn fl">
                    <em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="{% url 'users:logout' %}">退出</a>
                </div>
            {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'users:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'users:register' %}">注册</a>
                </div>
            {% endif %}
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'users:userinfo' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:info' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'order:info' 1%}">我的订单</a>
            </div>
        </div>
    </div>
</div>
<!-- 搜索框模块 -->
{% block search_bar %}rdadaw
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_num }}</div>
        </div>
    </div>
{% endblock search_bar %}
<!-- 主题  Body    模块  预留-->
{% block body %}{% endblock body %}

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
<!-- 底部foot模块预留 -->
{% block footer %}{% endblock footer %}
<!-- 预留空白模块 -->
{% block bottom_files %}{% endblock bottom_files %}

</body>
</html>

templates/list.html
{% extends 'base.html' %}

{% block title %}
    天天生鲜-商品列表
{% endblock title %}
{% block body %}

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for category in categorys %}
                        <!-- 点分类的名字跳到分类列表 传分类id 和 第几页 默认跳第一页 -->
                        <li><a href="{% url 'goods:list' category.id 1 %}?sort=default"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <!-- 全部分类进入首页 /  or /index -->
        <a href="{% url 'goods:index' %}">全部分类</a>
        <span>></span>
        <!-- 当前分类点自己不跳转 -->
        <a href="#">{{ category.name }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for new_sku in new_skus %}
                        <li>
                            <!-- sku涉及到的跳转到商品详情页 传 => sku id 过去获取详情页  -->
                            <a href="{% url 'goods:detail' new_sku.id %}"><img
                                    src="{{ new_sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
                        </li>
                    {% endfor %}


                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                {#        category.id 后台传过来的（最前面点进来分类的时候传进来的分类再传回来）, 分类id       #}
                <a href="{% url 'goods:list' category.id 1 %}?sort=default"
                   {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=price"
                        {#       高亮是class="active" 后台sort来控制的，后台sort是前台用户点过来的url里面，点击排序之后传到后台非法操作等安全处理后在模板中判断sort            #}
                   {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for page_sku in page_skus %}

                    <li>
                        <!-- sku涉及到的跳转到商品详情页 传 => sku id 过去获取详情页  -->
                        <a href="{% url 'goods:detail' page_sku.id %}"><img src="{{ page_sku.default_image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' page_sku.id %}">{{ page_sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ page_sku.price }}</span>
                            <span class="unit">{{ page_sku.price }}/{{ page_sku.unit }}</span>
                            <!-- 购物车模块 -->
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagenation">

                {% if  page_skus.has_previous %}
                    {#          过滤器的方式   这里index访问不到 page_skus.number替代     #}
                    <a href="{% url 'goods:list' category.id page_skus.number|add:-1 %}?sort={{ sort }}">
                        上一页
                    </a>
                {% endif %}

                {% for index in page_list %}
                                            <!-- 分页是第几页循环到几，排序不随页数改变一直往后传递 -->
                    <a href="{% url 'goods:list' category.id index %}?sort={{ sort }}"
                       {% if page_skus.number == index %}class="active"{% endif %}>{{ index }}</a>
                {% endfor %}

                {% if  page_skus.has_next %}
                    {#          直接调用现成的方法 page.next_page_number | previos_page_number        #}
                    <a href="{% url 'goods:list' category.id page_skus.next_page_number %}?sort={{ sort }}">
                        下一页
                    </a>
                {% endif %}

                <a href="#">></a>
            </div>
        </div>
    </div>
{% endblock body %}

templates/order_comment.html
{% extends 'user_center_base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-用户中心{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'users:userinfo' %}">· 个人信息</a></li>
                <li><a href="{% url 'order:info' 1 %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'users:address' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">订单评价</h3>
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
                <li class="col02 stress">{{ order.status_name }}</li>
            </ul>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{ order.order_id }}">
                <input type="hidden" name="total_count" value="{{ order.skus|length }}">
                {% for sku in order.skus %}
                    <table class="order_list_table w980">
                        <tbody>
                        <tr>
                            <td width="80%">
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ sku.default_image.url }}"></li>
                                    <li class="col02">{{ sku.name }}<em>{{ sku.price }}/{{ sku.unit }}</em></li>
                                    <li class="col03">{{ sku.count }}</li>
                                </ul>
                            </td>
                            <td width="20%">{{ sku.amount }}元</td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="site_con">
                        <input type="hidden" name="sku_{{ forloop.counter }}" value="{{ sku.id }}">
                        <div class="form_group form_group2">
                            <label>评价内容：</label>
                            <textarea class="site_area" name="content_{{ forloop.counter }}"></textarea>
                        </div>
                    </div>
                {% endfor %}
                <input type="submit" name="" value="提交" class="info_submit">
            </form>
        </div>
    </div>
{% endblock %}

templates/user_center_base.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}天天生鲜-用户中心{% endblock title %}
<!-- 只重写了搜索框模块，因为用户中心没有购物车 -->
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="search_con fr">
            <form method="get" action="/search/">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
    </div>
{% endblock search_bar %}

templates/user_center_info.html
{% extends 'base.html' %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'users:userinfo' %}" class="active">· 个人信息</a></li>
                <li><a href="{% url 'order:info' 1 %}">· 全部订单</a></li>
                <li><a href="{% url 'users:address' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名：</span>{{ user.username }}</li>
                    <li><span>联系方式：</span>{{ user_lastest_address_model.receiver_mobile }}</li>
                    <li><span>联系地址：</span>{{ user_lastest_address_model.detail_addr }}</li>
                </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {% for sku_model in sku_model_list %}
                        <li>         <!-- 传的就是ＧｏｏｄｓＳｋｕ的ｉｄ刚好 -->
                            <a href="{% url 'goods:detail' sku_model.id %}"><img
                                    src="{{ sku_model.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku_model.id %}">{{ sku_model.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ sku_model.price }}</span>
                                <span class="unit">{{ sku_model.price }}/{{ sku_model.unit }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}